### ISSUE TITLE
Lacking README

### ISSUE THREAD

**Issue by michael-jonas** [LaurierMantel/uwhksa#1]
Hey Laurier some people might be confused as to what this repo is for without a readme. Consider putting one in.

**Comment by karanthukral** [comment]
README is the first step in stepping away from the project's unsuccessful past 👍

**Comment by karanthukral** [comment]
@LaurierMantel  

PR: https://github.com/LaurierMantel/uwhksa/pull/2

**Comment by karanthukral** [comment]
Merged
